source "http://rubygems.org"

gem "rails", "3.0.10"
gem "image_management", :git => "git://github.com/jguiditta/image-management-engine.git"

group :development, :test do
  gem "capybara", ">= 0.4.0"
  gem "sqlite3"
end

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'
